name: 'GitHub Actions build and deploy github pages'

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md # 忽略
      - scaffolds

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: echo "$CC"
      - run: git config --global user.email ${{ secrets.MY_USER_EMAIL }}
      - run: git config --global user.name ${{ secrets.MY_USER_NAME }}
      - run: npm ci
      - run: npm run build
      - run: sh .github/workflows/deploy.sh
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
          CC: ${{ toJSON(github) }}

