name: 'GitHub Actions build and deploy github pages'

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: git config --global user.email "xybin1990@163.com"
      - run: git config --global user.name "xybin1990"
      - run: npm ci
      - run: npm run build && npm run deploy
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}

